### ISSUE TITLE
Umlaute beim Hochladen unter Bilder und Dateien falsch aufgelöst

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/NavEditor#10]
Sowohl in der aktuellen Testversion 2.13.0618 als auch in der aktuellen stabilen Version 2.13.0306:
(vermutlich) bei Windows werden Umlaute beim Hochladen weggelassen, beim Mac wird z.B. aus ä nur ein a
ging aber meiner Meinung nach in einer früheren Version schon mal einwandfrei

**Comment by xwolfde** [comment]
Das ist Absicht - es gab wegen unterschiedlichster Charsets der Systeme dauernd Probleme mit Umlauten und Sonderzeichen in Dateinamen. Zwar nicht beim Hochladen, aber beim Abruf der Datei übers Netz.

Daher werden alle Zeichen die nicht im ASCII enthalten sind, auf deren Pendant umgesetzt.

**Comment by endv02** [comment]
Sorry, evtl. missverständlich formuliert: Auflösen der Umlaute ist schon klar, aber sollte doch aus Gründen der besseren Lesbarkeit in der Form geschehen (so war es auch eine Zeit lang):
ä - ae, ö - oe, ü - ue, ß - ss
De facto geschieht es gerade aber so, dass (vermutlich betriebssystemabhängig) die Umlaute weggelassen oder falsch aufgelöst werden, sprich aus der Datei "Geräteinfo.pdf" wurde einmal "gerteinfo.pdf" und an einem anderen Rechner "gerateinfo.pdf", und nicht "geraeteinfo.pdf", wie zu erwarten ist.
